-- Dữ liệu thật từ thư mục file-goc (11 files)
-- Generated automatically from actual files in public/images/file-goc

INSERT INTO file_documents (
  name, original_name, file_name, file_path, file_size, file_type, mime_type, 
  category_id, description, tags, uploaded_by, is_active, download_count
) VALUES 
(
  'GIẢI PHÁP ĐỘT PHÁ 6 THÁNG CUỐI NĂM 2025 - PPBL',
  '250625 GIẢI PHÁP ĐỘT PHÁ 6 THÁNG CUỐI NĂM 2025 - PPBL.pptx',
  'giai_phap_dot_pha_2025_ppbl.pptx',
  '/images/file-goc/250625 GIẢI PHÁP ĐỘT PHÁ 6 THÁNG CUỐI NĂM 2025 - PPBL.pptx',
  5329291,
  'powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'business-plans',
  'Tài liệu trình bày giải pháp đột phá cho 6 tháng cuối năm 2025 của Phòng Phát triển Bưu chính Logistics',
  ARRAY['Kế hoạch', '2025', 'Thuyết trình', 'Bưu chính'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  45
),
(
  'Slide Nội dung trao đổi BDT TP về BĐX tỉnh thí điểm',
  '3107 slide Noi dung trao doi BDT TP ve BĐX_tỉnh thí điểm.pptx',
  'slide_noi_dung_trao_doi_bdt_tp.pptx',
  '/images/file-goc/3107 slide Noi dung trao doi BDT TP ve BĐX_tỉnh thí điểm.pptx',
  2799322,
  'powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'administrative',
  'Slide trao đổi nội dung giữa Ban Điều tra Trung ương và các tỉnh thí điểm về cải cách hành chính',
  ARRAY['Thuyết trình', 'Hành chính', 'Thí điểm'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  32
),
(
  'Gia hạn khối lượng BG TMĐT đồng giá',
  '4020. Gia han khôi luong BG TMĐT đồng giá.pdf',
  'gia_han_khoi_luong_bg_tmdt.pdf',
  '/images/file-goc/4020. Gia han khôi luong BG TMĐT đồng giá.pdf',
  1392844,
  'pdf',
  'application/pdf',
  'regulations',
  'Quyết định gia hạn thực hiện chính sách khối lượng Bưu gửi Thương mại điện tử đồng giá',
  ARRAY['Quyết định', 'Bưu chính', 'TMĐT', 'Giá cước'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  28
),
(
  'HƯỚNG DẪN XÂY DỰNG KHHD',
  '6.1 HUONG DAN XAY DUNG KHHD.xlsx',
  'huong_dan_xay_dung_khhd.xlsx',
  '/images/file-goc/6.1 HUONG DAN XAY DUNG KHHD.xlsx',
  30584,
  'excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'administrative',
  'Tài liệu hướng dẫn chi tiết quy trình xây dựng Kế hoạch Hoạt động hàng năm',
  ARRAY['Hướng dẫn', 'Kế hoạch', 'Hành chính'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  56
),
(
  'BHHS Bản chào DBV DNB VNPOST - Thống Nhất',
  'BHHS_Bản chào_DBV DNB_VNPOST_Chỉ áp dụng đia bàn huyện Thống Nhất củ - final.docx',
  'bhhs_ban_chao_dbv_dnb_vnpost_thong_nhat.docx',
  '/images/file-goc/BHHS_Bản chào_DBV DNB_VNPOST_Chỉ áp dụng đia bàn huyện Thống Nhất củ - final.docx',
  4016429,
  'word',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'insurance-health',
  'Bản đề xuất chính sách Bảo hiểm Hỗ trợ Sức khỏe của VNPOST Đông Nam Bộ cho khu vực huyện Thống Nhất',
  ARRAY['BHYT', 'VNPOST', 'Thống Nhất', 'Phiên bản cuối'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  41
),
(
  'Cước dịch vụ Tiêu chuẩn hàng nặng cồng kềnh V1',
  'Cước dịch vụ Tiêu chuẩn hàng nặng cồng kềnh (V1) CTN025.docx',
  'cuoc_dich_vu_tieu_chuan_hang_nang_cong_kenh.docx',
  '/images/file-goc/Cước dịch vụ Tiêu chuẩn hàng nặng cồng kềnh (V1) CTN025.docx',
  90743,
  'word',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'postal-services',
  'Bảng cước phí dịch vụ chuyển phát hàng nặng và cồng kềnh theo tiêu chuẩn mới phiên bản 1',
  ARRAY['Giá cước', 'Bưu chính', 'Phiên bản'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  67
),
(
  'DỊCH VỤ BƯU CHÍNH CHUYỂN PHÁT QT VÀ TRONG NƯỚC',
  'DICH VU BƯU CHÍNH CHUYỂN PHÁT QT VÀ TRONG NƯỚC.pdf',
  'dich_vu_buu_chinh_chuyen_phat_qt_trong_nuoc.pdf',
  '/images/file-goc/DICH VU BƯU CHÍNH CHUYỂN PHÁT QT VÀ TRONG NƯỚC.pdf',
  10882157,
  'pdf',
  'application/pdf',
  'postal-services',
  'Tổng quan về các dịch vụ Bưu chính Chuyển phát Quốc tế và Trong nước của VNPOST',
  ARRAY['Bưu chính', 'Dịch vụ'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  89
),
(
  'Dịch vụ công đầu giây',
  'dich-vu-cong-dau-giay.jpg',
  'dich_vu_cong_dau_giay.jpg',
  '/images/file-goc/dich-vu-cong-dau-giay.jpg',
  338126,
  'image',
  'image/jpeg',
  'administrative',
  'Hình ảnh minh họa về dịch vụ công trực tuyến đầu giây, thể hiện tính tiện lợi và nhanh chóng',
  ARRAY['Dịch vụ công'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  23
),
(
  'QUYẾT ĐỊNH GIAO CHỈ TIÊU BHYT TẠI XÃ THỐNG NHẤT',
  'QUYẾT ĐỊNH GIAO CHỈ TIÊU BHYT TẠI XÃ THỐNG NHẤT.pdf',
  'quyet_dinh_giao_chi_tieu_bhyt_thong_nhat.pdf',
  '/images/file-goc/QUYẾT ĐỊNH GIAO CHỈ TIÊU BHYT TẠI XÃ THỐNG NHẤT.pdf',
  579827,
  'pdf',
  'application/pdf',
  'insurance-health',
  'Quyết định phân bổ và giao chỉ tiêu thực hiện Bảo hiểm Y tế tại địa bàn Xã Thống Nhất',
  ARRAY['Quyết định', 'BHYT', 'Thống Nhất'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  34
),
(
  'QĐ ban hành giá vốn DV E-commerce đi Mỹ',
  'QĐ ban hành giá vốn DV E-commerce đi Mỹ 10.9.pdf',
  'qd_ban_hanh_gia_von_dv_ecommerce_my.pdf',
  '/images/file-goc/QĐ ban hành giá vốn DV E-commerce đi Mỹ 10.9.pdf',
  2568350,
  'pdf',
  'application/pdf',
  'postal-services',
  'Quyết định ban hành giá vốn dịch vụ E-commerce gửi hàng đi Mỹ áp dụng từ ngày 10/9',
  ARRAY['Quyết định', 'E-commerce', 'Giá cước', 'Bưu chính'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  52
),
(
  'Thư ngỏ Phí HS-GV năm học 2025-2026',
  'Thư ngỏ_ Phí HS-GV-năm học 2025-2026 .doc',
  'thu_ngo_phi_hs_gv_2025_2026.doc',
  '/images/file-goc/Thư ngỏ_ Phí HS-GV-năm học 2025-2026 .doc',
  150016,
  'word',
  'application/msword',
  'education',
  'Thư ngỏ thông báo về mức phí đóng góp Học sinh - Giáo viên cho năm học 2025-2026',
  ARRAY['Giáo dục', 'Thông báo', '2025'],
  (SELECT id FROM auth.users LIMIT 1),
  true,
  19
);